### PR TITLE
Support custom root file

### LINKED ISSUE #41: Unable to specify custom index file
I have an angular project that contains a different name for the index file. This configuration is provided in the angular.json under the build options.

Since, angular-http-server only serves index.html. I have to rename this file for testing purpose.

An option to provide the rootFile as part of the cli option would be great.

**node angular-http-server.js --rootFile myfile.html --path example --ssl -p 9000**

### PR DESCRIPTION
**Pull request by amkhapare**
closes #41 

1. Added support to specify a custom rootfile

### CODE REVIEW

**Comment by simonh1000** [comment]
I tried to test this with the commands that github suggests
```
git checkout -b amkhapare-support-custom-rootfile master
git pull https://github.com/amkhapare/angular-http-server.git support-custom-rootfile
```
but i end up with `fatal: refusing to merge unrelated histories`. 

This is confusing because github otherwise seems content to merge your branch. But I looked at your repo and it does seem to be different to mine in other ways. Can i suggest that you fork by code again and apply your changes to that?

(Note that you do not need to include the example2 directory as that is not needed)

**Comment by simonh1000** [comment]
... and add yourself to the contributors in package.json :-)

**Comment by amkhapare** [comment]
1. Removed example2.
2. rebase with updated fork.

**Comment by simonh1000** [comment]
Thanks will test as soon as I have time - perhaps at the weekend

**Comment by simonh1000** [comment]
Looks good - thanks

**Pull request merged**
