### PR TITLE
Added functionality to specify a port

### PR DESCRIPTION
**Pull request by greenygh0st**
First off fantastic accomplished exactly what I needed - serve an Angular SPA site with no overly fancy bells and whistles.

But there was a feature I found that it lacked which made it impossible to use on our internal Dokku server - that was the lack of ability to specify a port. Since Dokku manages the port for you in the Procfile by you passing $PORT as a parameter it was causing a bit of chaos.

What I added - a library to make it a little easier to parse out CLI arguments. Then there is one added function which checks for the presence of the argument and if it's a number. If the argument is present and it is a number it will be passed as the return value which is then used by server.listen.

If the port argument is not present the default 8080 port is returned and if the argument is present but not a number an exception will be thrown.

I also went ahead and bumped the version number as well.

### CODE REVIEW

**Comment by simonh1000** [comment]
Sounds great - I will take a look (hopefully this weekend) - thanks so much

**Comment by simonh1000** [comment]
Thanks a lot

**Comment by greenygh0st** [comment]
Awesome and no problem! Thanks for the merge. :)

**Comment by simonh1000** [comment]
Don't for get to star the project now that you are a contributor ;-)

**Comment by greenygh0st** [comment]
Ha oops. Done. :)

**Pull request merged**
